# Before trtiggering this action, be sure to run the following once locally and push the created files
# pydoc-markdown --bootstrap mkdocs
# pydoc-markdown --bootstrap readthedocs
name: Generate markdown in docs folder

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.x' 
    
    - name: Install Dependencies
      run: |
        python3 -m pip install pydoc-markdown
        python3 -m pip install mkdocs
        python3 -m pip install mkdocs-gitbook
        
    - name: Generate and Move Documentation
      run: |
        pydoc-markdown
        
        cd build/docs/
        mkdocs build
        
        cd ../..        
        mv build/docs/site/* docs/
        cp -avr diagrams/ docs/
      
    - name: Open docs update PR
      uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

